### ISSUE TITLE
Introduce synchronous signatures

### ISSUE THREAD

**Issue by gibson042** [IndigoUnited/node-proper-lockfile#1]
* `.lockSync(file, [options])` returns the release function or throws an `err-code` exception
* `.unlockSync(file, [options])` returns the release function or throws an `err-code` exception

As https://github.com/npm/lockfile#methods puts it:
> Sync methods return the value/throw the error, others don't. Standard node fs stuff.

**Comment by satazor** [comment]
That would be a cool addition. You ca already so this by passing a custom fs in the functions wrapping async execution. Thought its a bit cumbersome to so that manually.

**Comment by satazor** [comment]
Oops closed by mistake

**Comment by satazor** [comment]
What I was saying is that we can easily do lockSync and unlockAsync by injecting a custom fs into the options with async functions that are actually sync. Doing it like that would be straightforward and would not introduce complexity.

**Comment by gibson042** [comment]
I like that as an implementation principle, but there are two aspects necessary to keep it accordance with [http://nodejs.org/api/fs.html](http://nodejs.org/api/fs.html) (and [https://github.com/npm/lockfile](https://github.com/npm/lockfile#methods), for that matter): synchronous behavior, and a signature that returns/throws instead of accepting a callback. Dropping in a synchronous `fs` would address only the first.

**Comment by satazor** [comment]
Yes I agree. I would agree to add `lockSync` and `unlockSync` that return/throws like you expect, but internally it wraps `options.fs` with sync behavior. Would you have time to do PR?

**Comment by satazor** [comment]
@gibson042 can you take a look at https://github.com/IndigoUnited/node-proper-lockfile/commit/57261842200a2a0477fe3ce00bcbbe9d996d1346 ? It's working nicely.

**Comment by satazor** [comment]
Landed in `1.0.0`.

**Comment by gibson042** [comment]
Sorry I didn't get a chance to pick this up myself, but the changes look great. Thank you very much.
