### ISSUE TITLE
lock file prior to existence

### ISSUE THREAD

**Issue by bmeck** [IndigoUnited/node-proper-lockfile#2]
right now you cannot `lock()` a file unless it is already on disk, this makes it hard to guarantee that files can be locked while their content is still being generated but the filename needs to be reserved

**Comment by satazor** [comment]
Indeed, the issue is with the `canonicalPath`. I need to get the canonical path of the file to ensure that calls to lock() with relative/absolute/etc are resolved to the same file.

I could detect a ENOENT error and just fallback to `path.normalize`. What od you think?

**Comment by bmeck** [comment]
that sounds fine

**Comment by satazor** [comment]
I ended up taking another approach. I've changed the `resolve` option to `realpath`.
By default `realpath` is enabled to resolve symlinks. If you turn it off, it will skip that step and will also allow locking files that are not yet created. Will publish 0.6 shortly.

**Comment by satazor** [comment]
Done.
