### ISSUE TITLE
Anyway to check if a file is locked without acquiring a lock?

### ISSUE THREAD

**Issue by timbowhite** [IndigoUnited/node-proper-lockfile#22]
Hi thanks for this module.
How can I check if a file is locked without acquiring a lock, similar to [lockfile.check](https://www.npmjs.com/package/lockfile#lockfilecheckpath-opts-cb)?

**Comment by satazor** [comment]
There is no equivalent functionality atm but feel free to drop a PR

**Comment by timbowhite** [comment]
OK just submitted PR #23.  I tried to do it without ripping up your current code too much.  Added a isLockStale function for comparing stat.mtime that is reused between .check() and .lock().
