### ISSUE TITLE
Uncaught Exception

### ISSUE THREAD

**Issue by DGollings** [IndigoUnited/node-proper-lockfile#5]
proper-lockfile/index.js:86
    lock.updateDelay = lock.updateDelay || options.update;
                           ^
TypeError: Cannot read property 'updateDelay' of undefined
    at updateLock (proper-lockfile/index.js:86:28)
    at proper-lockfile/index.js:119:13
    at Object.oncomplete (evalmachine.<anonymous>:107:15)

Not sure what causes the error, but I'd prefer an err object vs an exception

**Comment by satazor** [comment]
The error seems to be related to the internal mechanism of keeping the lock fresh. Can you provide more information about your system (os version, node version) as well as how are you using lockfile? thanks

**Comment by DGollings** [comment]
Sorry for not responding earlier, I think this is my fault. I'll update if so

**Comment by bmeck** [comment]
@DGollings any news?

**Comment by DGollings** [comment]
The occasional unexplained error, but the bulk of it was definitely my fault (I gave the lockfile import/require and a random function the same name. Meaning my options array wasn't used).

Considering the hacky way I'm using it, volume mount in docker + nfs, consider this issue closed.

Thanks,
D
